export const quotes = [
  "Ilana: 'You said if you were ever going to do same sex experimentation, it was going to be with me.'\nAbbi: 'I never said that to you.'\nIlana: 'It has been implied.'\nAbbi: 'By you.'",
  "Abbie: 'Who would you rather go down on you? Michael Bublé or Janet Jackson?'\nIlana: 'Can Janet Jackson go down on me while Michael Bublé narrates it in song?'",
  "Abbi: 'What is your return policy?'\nCashier: 'It's 30 days.'\nAbbi: 'Great, I'll see you in 30 days then....biiiiiitch.",
  "Ilana: 'I also have business with the bank. I’d like to cash these nickels, and I’ll have them in quarters, please. Thank you so much.'",
  "Ilana: 'I’m a sexual X-Man. I’m Wolverine. I’m Vulvarine!'",
  "Ilana: 'The vah-yine-yah is nature’s pocket. It’s natural and responsible.'",
  "Ilana: 'I'm not sexually aroused, I'm fiscally aroused.'",
  "Abbi: 'I got one, a gynecologist that’s also a bikini waxer.'\nIlana: 'That's literally a one stop pussy shop. I love it!'",
  "Ilana: 'Wanna fooook?!'",
  "Ilana: 'Four R’s, my friend: Reduce, Reuse, Recycle, Rihanna.'",
  "Ilana: 'Check it. I got a dirty ass martini and clean white power suit.'\nAbbi: 'I don’t know if I would call it a white power suit, especially after you talked about that ethnic smorgasbord of unpaid workers.'",
  "Abbi: 'I finally masturbated above the covers without my eyes being closed. That was a really big journal entry.'",
  "Ilana: 'Nomo FOMO'",
  "Abbi: 'I can't really imagine what it's like for people with blue eyes.'\nIlana: 'No idea, other than feeling like a fucking freak'",
  "Ilana: 'Abbi, truth or dare?\nAbbi: 'You know what, I'm gonna go with dare'\nIlana: I dare you to suck Jeremy's dick.'",
  "Ilana: 'That's cool. I respect you, respecting me. I am going to respect your dick later.'",
  "Ilana: 'You're leaving me like tight and dry.'",
  "Lincoln: 'I won't make out with you; white people do that, black people don't make out with dogs'",
  "Lincoln: 'I was so worried I baked a whole cake. And then I ate a whole cake.'",
  "Ilana: 'I leave a cum trail wherever I go, kinda like a slutty slug.'",
  "Ilana: 'Abbi, why wouldn't we be rating them on dick size? It's all I can see. Those b-ball shorts are God's gift. If you train your eyes, you can see their religion.",
  "Ilana: 'Nose, vagina, butthole. If God didn't want us to put our fingers in there, then why did he make them perfectly finger-sized?'",
  "Ilana: 'Do you ever get hair from your head stuck in buttcrack in the shower?'",
];
